# Product API
catalog_rest_products:
    resource: "@AiCatalogBundle/Controller/ProductApiController.php"
    prefix:   /api
    type:     annotation

# ApiDocs
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# OAuth
notes_oauth_token:
    path:  /token
    defaults: { _controller: fos_oauth_server.controller.token:tokenAction }
    requirements:
        _method:  POST
