security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:
            pattern:    ^/oauth/token
            security:   false

        api:
            pattern:   ^/api
            stateless: true
            fos_oauth: true
            anonymous: false

        security:
            pattern:    ^/
            security:   true
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
            logout:
                path:   /user/logout
            anonymous: true

    access_control:
        - { path: ^/oauth/auth$, roles: IS_AUTHENTICATED_FULLY }
